var dis = [
  'acquired immuno-deficiency syndrome',
  'adenocarcinoma',
  'adhesion',
  '	chronic alcoholic intoxication',
  'Alzheimer\'s disease',
  'anemia',
  'sickle cell anemia',
  'stenosis aortic valve',
  'aphasia',
  'arthritis',
  'asthma',
  'bacteremia',
  'benign prostatic hypertrophy',
  'bipolar disorder',
  'spasm bronchial',
  'bronchitis',
  'malignant neoplasms',
  'oral candidiasis',
  'carcinoma',
  'malignant tumor of colon',
  'cellulitis',
  'transient ischemic attack',
  'cholecystitis',
  'cholelithiasis',
  'colitis',
  'confusion',
  'coronary arteriosclerosis',
  'decubitus ulcer',
  'deglutition disorder',
  'dehydration',
  'delirium',
  'delusion',
  'depressive disorder',
  'diabetes',
  'ketoacidosis diabetic',
  'diverticulitis',
  'paroxysmal dyspnea',
  'endocarditis',
  'epilepsy',
  'epilepsy',
  'gastritis',
  'gastroenteritis',
  'gastroesophageal reflux disease',
  'glaucoma',
  'gout',
  'failure heart',
  'failure heart congestive',
  'hemiparesis',
  'hemorrhoids',
  'hepatitis',
  'hepatitis B',
  'hepatitis C',
  'primary carcinoma of the liver cells',
  'hernia',
  'hernia hiatal',
  'hiv infections',
  'hypercholesterolemia',
  'hyperglycemia',
  'hyperlipidemia',
  'hypertensive disease',
  'hypertension pulmonary',
  'hypoglycemia',
  'hypothyroidism',
  'incontinence',
  'infection',
  'influenza',
  'influenza',
  'kidney disease',
  'kidney failure acute',
  'chronic kidney failure',
  'fibroid tumor',
  'chronic obstructive airway disease',
  'lymphatic diseases',
  'lymphoma',
  'manic disorder',
  'melanoma',
  'mitral valve insufficiency',
  'myocardial infarction',
  'neoplasm metastasis',
  'neoplasm',
  'neutropenia',
  'obesity',
  'obesity morbid',
  'degenerative polyarthritis',
  'osteomyelitis',
  'osteoporosis',
  'pancreatitis',
  'pancytopenia',
  'parkinson disease',
  'ulcer peptic',
  'effusion pericardial',
  'personality disorder',
  'pneumonia',
  'pneumonia aspiration',
  'Pneumocystis carinii pneumonia',
  'pneumothorax',
  'psychotic disorder',
  'edema pulmonary',
  'embolism pulmonary',
  'emphysema pulmonary',
  'emphysema pulmonary',
  'failure kidney',
  'schizophrenia',
  'accident cerebrovascular',
  'tachycardia sinus',
  'thrombocytopaenia',
  'tricuspid valve insufficiency',
  'upper respiratory infection',
  'infection urinary tract',
  'peripheral vascular disease',
  'encephalopathy',
  'thrombus',
  'deep vein thrombosis',
  'migraine disorders',
  'affect labile',
  'biliary calculus',
  'systemic infection',
  'dependence',
  'neuropathy',
  'tonic-clonic seizures',
  'carcinoma prostate',
  'carcinoma breast',
  'carcinoma of lung',
  'anxiety state',
  'cardiomyopathy',
  'respiratory failure',
  'ileus',
  'paranoia',
  'diverticulosis',
  'insufficiency renal',
  'cirrhosis'
];
