var dis = [
  'acquired immuno-deficiency syndrome',
  'adenocarcinoma',
  'adhesion',
  '	chronic alcoholic intoxication',
  'Alzheimer\'s disease',
  'anemia',
  'sickle cell anemia',
  'stenosis aortic valve',
  'aphasia',
  'arthritis',
  'asthma',
  'bacteremia',
  'benign prostatic hypertrophy',
  'bipolar disorder',
  'spasm bronchial',
  'bronchitis',
  'malignant neoplasms',
  'oral candidiasis',
  'carcinoma',
  'malignant tumor of colon',
  'cellulitis',
  'transient ischemic attack',
  'cholecystitis',
  'cholelithiasis',
  'colitis',
  'confusion',
  'coronary arteriosclerosis',
  'decubitus ulcer',
  'deglutition disorder',
  'dehydration',
  'delirium',
  'delusion',
  'depressive disorder',
  'diabetes',
  'ketoacidosis diabetic',
  'diverticulitis',
  'paroxysmal dyspnea',
  'endocarditis',
  'epilepsy',
  'epilepsy',
  'gastritis',
  'gastroenteritis',
  'gastroesophageal reflux disease',
  'glaucoma',
  'gout',
  'failure heart',
  'failure heart congestive',
  'hemiparesis',
  'hemorrhoids',
  'hepatitis',
  'hepatitis B',
  'hepatitis C',
  'primary carcinoma of the liver cells',
  'hernia',
  'hernia hiatal',
  'hiv infections',
  'hypercholesterolemia',
  'hyperglycemia',
  'hyperlipidemia',
  'hypertensive disease',
  'hypertension pulmonary',
  'hypoglycemia',
  'hypothyroidism',
  'incontinence',
  'infection',
  'influenza',
  'influenza',
  'kidney disease',
  'kidney failure acute',
  'chronic kidney failure',
  'fibroid tumor',
  'chronic obstructive airway disease',
  'lymphatic diseases',
  'lymphoma',
  'manic disorder',
  'melanoma',
  'mitral valve insufficiency',
  'myocardial infarction',
  'neoplasm metastasis',
  'neoplasm',
  'neutropenia',
  'obesity',
  'obesity morbid',
  'degenerative polyarthritis',
  'osteomyelitis',
  'osteoporosis',
  'pancreatitis',
  'pancytopenia',
  'parkinson disease',
  'ulcer peptic',
  'effusion pericardial',
  'personality disorder',
  'pneumonia',
  'pneumonia aspiration',
  'Pneumocystis carinii pneumonia',
  'pneumothorax',
  'psychotic disorder',
  'edema pulmonary',
  'embolism pulmonary',
  'emphysema pulmonary',
  'emphysema pulmonary',
  'failure kidney',
  'schizophrenia',
  'accident cerebrovascular',
  'tachycardia sinus',
  'thrombocytopaenia',
  'tricuspid valve insufficiency',
  'upper respiratory infection',
  'infection urinary tract',
  'peripheral vascular disease',
  'encephalopathy',
  'thrombus',
  'deep vein thrombosis',
  'migraine disorders',
  'affect labile',
  'biliary calculus',
  'systemic infection',
  'dependence',
  'neuropathy',
  'tonic-clonic seizures',
  'carcinoma prostate',
  'carcinoma breast',
  'carcinoma of lung',
  'anxiety state',
  'cardiomyopathy',
  'respiratory failure',
  'ileus',
  'paranoia',
  'diverticulosis',
  'insufficiency renal',
  'cirrhosis'
];

var sym = [
  'abdomen acute',
  'distended abdomen',
  'pain abdominal',
  'ambidexterity',
  'angina pectoris',
  'anorexia',
  'anosmia',
  'arthralgia',
  'ascites',
  'asthenia',
  'ataxia',
  'pain back',
  'breech presentation',
  'bruit',
  'cachexia',
  'catatonia',
  'pain neck',
  'pain chest',
  'pleuritic pain',
  'choke',
  'cicatrisation',
  'clonus',
  'constipation',
  'cough',
  'cyanosis',
  'diarrhea',
  'dizziness',
  'drool',
  'drowsiness',
  'dysarthria',
  'dyspnea',
  'dysuria',
  'ecchymosis',
  'enuresis',
  'fatigue',
  'fever',
  'flatulence',
  'flushing',
  'pain foot',
  'formication',
  'gag',
  'headache',
  'cardiomegaly',
  'heartburn',
  'Heberden\'s node',
  'hematochezia',
  'hematuria',
  'hemiplegia',
  'haemoptysis',
  'haemorrhage',
  'hepatomegaly',
  'hepatosplenomegaly',
  'hirsutism',
  'hoarseness',
  'hunger',
  'hydropneumothorax',
  'hypercapnia',
  'hyperhidrosis disorder',
  'hyperkalemia',
  'hyperventilation',
  'hypesthesia',
  'hypocalcemia result',
  'hypokalemia',
  'hyponatremia',
  'hypoproteinemia',
  'hypotension',
  "hypothermia, natural",
  'irritable mood',
  'pain in lower limb',
  'lethargy',
  'low back pain',
  'mass in breast',
  'muscle hypotonia',
  'mydriasis',
  'myoclonus',
  'nausea',
  'nausea and vomiting',
  'nervousness',
  'night sweat',
  'nightmare',
  'numbness',
  'oliguria',
  'decreased translucency',
  'pain',
  'pallor',
  'palpitation',
  'panic',
  'paresis',
  'paresthesia',
  'polyuria',
  'posterior rhinorrhea',
  'pruritus',
  'lung nodule',
  'rale',
  'hyperacusis',
  'rhonchus',
  'sciatica',
  'seizure',
  'sneeze',
  'snore',
  'soft tissue swelling',
  'spasm',
  'splenomegaly',
  'stridor',
  'sweat',
  'swelling',
  'syncope',
  'tinnitus',
  'tremor',
  'unconscious state',
  'underweight',
  'erythema',
  'vertigo',
  'vomiting',
  'weight gain',
  'decreased body weight',
  'wheezing',
  'chill',
  'polydypsia',
  'urgency of micturition',
  'orthopnea',
  'burning sensation',
  'stupor',
  'agitation',
  'indifferent mood',
  'photopsia',
  'photophobia',
  'fall',
  'monocytosis',
  'hypokinesia',
  'food intolerance',
  'orthostasis',
  'poor dentition',
  'feeling hopeless',
  'urge incontinence',
  'neck stiffness',
  'bleeding of vagina',
  'qt interval prolonged',
  'urinary hesitation',
  'abortion',
  'sedentary',
  'thicken',
  'lightheadedness',
  'painful swallowing',
  'projectile vomiting',
  'paraparesis',
  'lesion',
  'welt',
  'aphagia',
  'decompensation',
  'malaise',
  'asymptomatic',
  'fatigability',
  'immobile',
  'myalgia',
  'muscle twitch',
  'titubation',
  'dyspnea on exertion',
  'tachypnea',
  'egophony',
  'fremitus',
  'pulsus paradoxus',
  'sinus rhythm',
  'systolic murmur',
  'pansystolic murmur',
  'pericardial friction rub',
  'chest tightness',
  'colic abdominal',
  'abdominal tenderness',
  'gurgle',
  'retch',
  'regurgitates after swallowing',
  'bowel sounds decreased',
  'tenesmus',
  'asterixis',
  'slowing of urinary stream',
  'pneumatouria',
  'intermenstrual heavy bleeding',
  'gravida',
  'previous pregnancies',
  'para',
  'para',
  'spontaneous rupture of membranes',
  'inappropriate affect',
  'worry',
  'elation',
  'bradykinesia',
  'neologism',
  'hallucinations auditory',
  'hallucinations visual',
  'clumsiness',
  'extrapyramidal sign',
  'sensory discomfort',
  'sore to touch',
  'ache',
  'rest pain',
  'tremor resting',
  'sleepy',
  'speech slurred',
  'todd paralysis',
  'barking cough',
  'dysdiadochokinesia',
  'feeling strange',
  'unable to concentrate',
  'pin-point pupils',
  'hyperemesis',
  'hypertonicity',
  'renal angle tenderness',
  'chest discomfort',
  'aura',
  'homelessness',
  'noisy respiration',
  'left atrial hypertrophy',
  'breath sounds decreased',
  'consciousness clear',
  'hacking cough',
  'productive cough',
  'satiety early',
  'estrogen use',
  'numbness of hand',
  'hypoalbuminemia',
  'jugular venous distention',
  'loose associations',
  'prodrome',
  'prostate tender',
  'scleral icterus',
  'pustule',
  'scar tissue',
  'sputum purulent',
  'stool color yellow',
  'unresponsiveness',
  'difficulty passing urine',
  'hypotonic',
  'uncoordination',
  'throat sore',
  'prostatism',
  'no known drug allergies',
  'nasal discharge present',
  'mediastinal shift',
  'tonic seizures',
  'hemianopsia homonymous',
  'Stahli\'s line',
  'extreme exhaustion',
  'apyrexial',
  'charleyhorse',
  'retropulsion',
  'nasal flaring',
  'pulse absent',
  'Murphy\'s sign',
  'decreased stool caliber',
  'excruciating pain',
  'shooting pain',
  'disequilibrium',
  'lameness',
  'blackout',
  'macule',
  'redness',
  'cushingoid facies',
  'nonsmoker',
  'impaired cognition',
  'vision blurred',
  'mood depressed',
  'hypometabolism',
  'patient non compliance',
  'clammy skin',
  'exhaustion',
  'shortness of breath',
  'dysesthesia',
  'giddy mood',
  'abnormal sensation',
  'rambling speech',
  'feeling suicidal',
  'verbal auditory hallucinations',
  'withdraw',
  'weepiness',
  'motor retardation',
  'behavior hyperactive',
  'hoard',
  'absences finding',
  'history of - blackout',
  'feels hot/feverish',
  'rigor - temperature-associated observation',
  'bedridden',
  'gasping for breath',
  'rapid shallow breathing',
  'catching breath',
  'cardiovascular finding',
  'stiffness',
  'facial paresis',
  'general unsteadiness',
  'rhd positive',
  'bradycardia',
  'r wave feature',
  'superimposition',
  'symptom aggravating factors',
  'suicidal',
  'pressure chest',
  'no status change',
  'milky',
  'homicidal thoughts',
  'energy increased',
  'large-for-dates fetus',
  'yellow sputum',
  'green sputum',
  'behavior showing increased motor activity',
  'feces in rectum',
  'distress respiratory',
  'breath-holding spell',
  'overweight',
  'st segment elevation',
  'st segment depression',
  't wave inverted',
  'coordination abnormal',
  'polymyalgia',
  'paralyse',
  'rolling of eyes',
  'awakening early',
  'dullness',
  'groggy',
  'incoherent',
  'lip smacking',
  'abscess bacterial',
  'labored breathing',
  'moody',
  'alcohol binge episode',
  'has religious belief',
  'tired',
  'verbally abusive behavior',
  'transsexual',
  'macerated skin',
  'wheelchair bound',
  'terrify',
  'sniffle',
  'adverse reaction',
  'poor feeding',
  'mass of body structure',
  'frothy sputum',
  'hemodynamically stable',
  'disturbed family',
  'heavy legs',
  'heavy feeling',
  'hot flush',
  'stinging sensation',
  'systolic ejection murmur',
  'hypoxemia',
  'sweating increased',
  'abnormally hard consistency',
  'intoxication',
  'air fluid level',
  'alcoholic withdrawal symptoms',
  'atypia',
  'debilitation',
  'emphysematous change',
  'guaiac positive',
  'hematocrit decreased',
  'heme positive',
  'monoclonal',
  'side pain',
  'hypersomnolence',
  'phonophobia',
  'focal seizures',
  'unhappy',
  'out of breath',
  'room spinning',
  'stuffy nose',
  'passed stones',
  'non-productive cough',
  'mental status changes',
  'dizzy spells',
  'red blotches',
  'unwell',
  'floppy',
  'general discomfort',
  'moan',
  'primigravida',
  'frail',
  'posturing',
  'fear of falling',
  'cushingoid habitus',
  'adverse effect',
  'hypersomnia',
  'sleeplessness',
  'blanch',
  'transaminitis',
  'breakthrough pain',
  'fecaluria',
  'snuffle',
  'tumor cell invasion',
  'unsteady gait',
  'abdominal bloating',
  'gravida 10',
  'difficulty',
  'presence of q wave',
  'urinoma',
  'cardiovascular event',
  'achalasia',
  'scratch marks',
  'dyspareunia',
  'proteinemia',
  'throbbing sensation quality',
  'claudication',
  'cystic lesion',
  'metastatic lesion',
  'flare',
];
